# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MOS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1054, 723)
        Form.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 6, 18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget_2.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"background-color: rgb(240, 240, 240);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(31, -95, 65, 25))
        self.label_16.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_16.setObjectName("label_16")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 140, 311, 176))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 3, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_21.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.Eg = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.Eg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Eg.setObjectName("Eg")
        self.gridLayout_2.addWidget(self.Eg, 1, 1, 1, 1)
        self.Qm = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.Qm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qm.setObjectName("Qm")
        self.gridLayout_2.addWidget(self.Qm, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 0, 1, 1)
        self.es = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.es.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.es.setObjectName("es")
        self.gridLayout_2.addWidget(self.es, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.XX = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.XX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.XX.setObjectName("XX")
        self.gridLayout_2.addWidget(self.XX, 2, 1, 1, 1)
        self.ni = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.ni.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.ni.setObjectName("ni")
        self.gridLayout_2.addWidget(self.ni, 0, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 304, 62))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Si = QtWidgets.QRadioButton(self.groupBox_7)
        self.Si.setChecked(True)
        self.Si.setObjectName("Si")
        self.horizontalLayout_4.addWidget(self.Si)
        self.Ge = QtWidgets.QRadioButton(self.groupBox_7)
        self.Ge.setObjectName("Ge")
        self.horizontalLayout_4.addWidget(self.Ge)
        self.GaAs = QtWidgets.QRadioButton(self.groupBox_7)
        self.GaAs.setObjectName("GaAs")
        self.horizontalLayout_4.addWidget(self.GaAs)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 70, 301, 61))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Al = QtWidgets.QRadioButton(self.groupBox_8)
        self.Al.setChecked(False)
        self.Al.setObjectName("Al")
        self.horizontalLayout_5.addWidget(self.Al)
        self.Ag = QtWidgets.QRadioButton(self.groupBox_8)
        self.Ag.setChecked(True)
        self.Ag.setObjectName("Ag")
        self.horizontalLayout_5.addWidget(self.Ag)
        self.An = QtWidgets.QRadioButton(self.groupBox_8)
        self.An.setObjectName("An")
        self.horizontalLayout_5.addWidget(self.An)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 301, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_39 = QtWidgets.QLabel(self.groupBox_9)
        self.label_39.setStyleSheet("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 2, 2, 1, 1)
        self.P = QtWidgets.QRadioButton(self.groupBox_9)
        self.P.setObjectName("P")
        self.gridLayout_3.addWidget(self.P, 1, 1, 1, 1)
        self.N = QtWidgets.QRadioButton(self.groupBox_9)
        self.N.setChecked(True)
        self.N.setObjectName("N")
        self.gridLayout_3.addWidget(self.N, 1, 0, 1, 1)
        self.NN = QtWidgets.QLineEdit(self.groupBox_9)
        self.NN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NN.setObjectName("NN")
        self.gridLayout_3.addWidget(self.NN, 2, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_9)
        self.label_38.setStyleSheet("")
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 2, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 141, 311, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Qss = QtWidgets.QLineEdit(self.layoutWidget)
        self.Qss.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qss.setObjectName("Qss")
        self.gridLayout_4.addWidget(self.Qss, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget)
        self.label_47.setStyleSheet("")
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 3, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        self.label_45.setStyleSheet("")
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 1, 2, 1, 1)
        self.L = QtWidgets.QLineEdit(self.layoutWidget)
        self.L.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.L.setObjectName("L")
        self.gridLayout_4.addWidget(self.L, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget)
        self.label_46.setStyleSheet("")
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 2, 2, 1, 1)
        self.VGS = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.VGS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VGS.setProperty("value", 1.0)
        self.VGS.setObjectName("VGS")
        self.gridLayout_4.addWidget(self.VGS, 3, 1, 1, 1)
        self.dffeedf = QtWidgets.QLabel(self.layoutWidget)
        self.dffeedf.setStyleSheet("")
        self.dffeedf.setObjectName("dffeedf")
        self.gridLayout_4.addWidget(self.dffeedf, 3, 0, 1, 1)
        self.rhgdg = QtWidgets.QLabel(self.layoutWidget)
        self.rhgdg.setStyleSheet("")
        self.rhgdg.setObjectName("rhgdg")
        self.gridLayout_4.addWidget(self.rhgdg, 2, 0, 1, 1)
        self.W = QtWidgets.QLineEdit(self.layoutWidget)
        self.W.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.W.setObjectName("W")
        self.gridLayout_4.addWidget(self.W, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget)
        self.label_40.setStyleSheet("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 0, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget)
        self.label_44.setStyleSheet("")
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 0, 2, 1, 1)
        self.wewwrfqwf = QtWidgets.QLabel(self.layoutWidget)
        self.wewwrfqwf.setStyleSheet("")
        self.wewwrfqwf.setObjectName("wewwrfqwf")
        self.gridLayout_4.addWidget(self.wewwrfqwf, 1, 0, 1, 1)
        self.dffeedf_2 = QtWidgets.QLabel(self.layoutWidget)
        self.dffeedf_2.setStyleSheet("")
        self.dffeedf_2.setObjectName("dffeedf_2")
        self.gridLayout_4.addWidget(self.dffeedf_2, 4, 0, 1, 1)
        self.tox = QtWidgets.QLineEdit(self.layoutWidget)
        self.tox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tox.setObjectName("tox")
        self.gridLayout_4.addWidget(self.tox, 4, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget)
        self.label_48.setStyleSheet("")
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 4, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(9, 9, 331, 281))
        self.groupBox_6.setStyleSheet("font: 75 10pt \"微软雅黑\";")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setContentsMargins(28, -1, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Ge_2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_2.setChecked(True)
        self.Ge_2.setObjectName("Ge_2")
        self.verticalLayout_8.addWidget(self.Ge_2)
        self.Ge_3 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_3.setObjectName("Ge_3")
        self.verticalLayout_8.addWidget(self.Ge_3)
        self.Ge_4 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_4.setObjectName("Ge_4")
        self.verticalLayout_8.addWidget(self.Ge_4)
        self.Ge_5 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_5.setObjectName("Ge_5")
        self.verticalLayout_8.addWidget(self.Ge_5)
        self.Ge_8 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_8.setObjectName("Ge_8")
        self.verticalLayout_8.addWidget(self.Ge_8)
        self.Ge_6 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_6.setObjectName("Ge_6")
        self.verticalLayout_8.addWidget(self.Ge_6)
        self.Ge_7 = QtWidgets.QRadioButton(self.groupBox_6)
        self.Ge_7.setObjectName("Ge_7")
        self.verticalLayout_8.addWidget(self.Ge_7)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.verticalLayout_7.addWidget(self.tabWidget_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.NCD = QtWidgets.QWidget()
        self.NCD.setObjectName("NCD")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.NCD)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.klnddvko = QtWidgets.QLabel(self.NCD)
        self.klnddvko.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.klnddvko.setObjectName("klnddvko")
        self.gridLayout_5.addWidget(self.klnddvko, 0, 0, 1, 1)
        self.Qfn = QtWidgets.QLineEdit(self.NCD)
        self.Qfn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qfn.setObjectName("Qfn")
        self.gridLayout_5.addWidget(self.Qfn, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.NCD)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 2, 1, 1)
        self.skjdhfbvk = QtWidgets.QLabel(self.NCD)
        self.skjdhfbvk.setObjectName("skjdhfbvk")
        self.gridLayout_5.addWidget(self.skjdhfbvk, 1, 0, 1, 1)
        self.Xdt = QtWidgets.QLineEdit(self.NCD)
        self.Xdt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Xdt.setObjectName("Xdt")
        self.gridLayout_5.addWidget(self.Xdt, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.NCD)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 2, 1, 1)
        self.Emax1 = QtWidgets.QLabel(self.NCD)
        self.Emax1.setObjectName("Emax1")
        self.gridLayout_5.addWidget(self.Emax1, 2, 0, 1, 1)
        self.Qsdmax = QtWidgets.QLineEdit(self.NCD)
        self.Qsdmax.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qsdmax.setObjectName("Qsdmax")
        self.gridLayout_5.addWidget(self.Qsdmax, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.NCD)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.NCD)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 3, 0, 1, 1)
        self.Qms = QtWidgets.QLineEdit(self.NCD)
        self.Qms.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qms.setText("")
        self.Qms.setObjectName("Qms")
        self.gridLayout_5.addWidget(self.Qms, 3, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.NCD)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.NCD)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 1)
        self.VTP = QtWidgets.QLineEdit(self.NCD)
        self.VTP.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VTP.setText("")
        self.VTP.setObjectName("VTP")
        self.gridLayout_5.addWidget(self.VTP, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.NCD)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 4, 2, 1, 1)
        self.tabWidget_3.addTab(self.NCD, "")
        self.PCD = QtWidgets.QWidget()
        self.PCD.setObjectName("PCD")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.PCD)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.klnddvko_2 = QtWidgets.QLabel(self.PCD)
        self.klnddvko_2.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.klnddvko_2.setObjectName("klnddvko_2")
        self.gridLayout_6.addWidget(self.klnddvko_2, 0, 0, 1, 1)
        self.Qfn_2 = QtWidgets.QLineEdit(self.PCD)
        self.Qfn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qfn_2.setObjectName("Qfn_2")
        self.gridLayout_6.addWidget(self.Qfn_2, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.PCD)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 0, 2, 1, 1)
        self.skjdhfbvk_2 = QtWidgets.QLabel(self.PCD)
        self.skjdhfbvk_2.setObjectName("skjdhfbvk_2")
        self.gridLayout_6.addWidget(self.skjdhfbvk_2, 1, 0, 1, 1)
        self.Xdt_2 = QtWidgets.QLineEdit(self.PCD)
        self.Xdt_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Xdt_2.setObjectName("Xdt_2")
        self.gridLayout_6.addWidget(self.Xdt_2, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.PCD)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 2, 1, 1)
        self.Emax1_2 = QtWidgets.QLabel(self.PCD)
        self.Emax1_2.setObjectName("Emax1_2")
        self.gridLayout_6.addWidget(self.Emax1_2, 2, 0, 1, 1)
        self.Qsdmax_2 = QtWidgets.QLineEdit(self.PCD)
        self.Qsdmax_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qsdmax_2.setObjectName("Qsdmax_2")
        self.gridLayout_6.addWidget(self.Qsdmax_2, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.PCD)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.PCD)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.Qms_2 = QtWidgets.QLineEdit(self.PCD)
        self.Qms_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Qms_2.setText("")
        self.Qms_2.setObjectName("Qms_2")
        self.gridLayout_6.addWidget(self.Qms_2, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.PCD)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 3, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.PCD)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 4, 0, 1, 1)
        self.VTP_2 = QtWidgets.QLineEdit(self.PCD)
        self.VTP_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VTP_2.setText("")
        self.VTP_2.setObjectName("VTP_2")
        self.gridLayout_6.addWidget(self.VTP_2, 4, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.PCD)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 4, 2, 1, 1)
        self.tabWidget_3.addTab(self.PCD, "")
        self.gridLayout.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 9)
        self.verticalLayout.setStretch(2, 6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 17)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 181, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_1.setGeometry(QtCore.QRect(40, 90, 181, 41))
        self.pushButton_1.setObjectName("pushButton_1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(240, 90, 181, 45))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout_2.addWidget(self.radioButton_1)
        self.runButton = QtWidgets.QPushButton(self.groupBox_4)
        self.runButton.setGeometry(QtCore.QRect(440, 30, 131, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.runButton.setFont(font)
        self.runButton.setStyleSheet("font: 75 16pt \"微软雅黑\";\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));")
        self.runButton.setObjectName("runButton")
        self.exit = QtWidgets.QPushButton(self.groupBox_4)
        self.exit.setGeometry(QtCore.QRect(240, 30, 181, 41))
        self.exit.setObjectName("exit")
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.verticalLayout_6.setStretch(0, 15)
        self.verticalLayout_6.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 5)

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "半导体器件仿真平台-MOSFET"))
        self.groupBox_2.setTitle(_translate("Form", "参数设置"))
        self.label_16.setText(_translate("Form", "  Xn： "))
        self.label_30.setText(_translate("Form", "   V"))
        self.label_25.setText(_translate("Form", "   V"))
        self.label_22.setText(_translate("Form", "  eV"))
        self.label_21.setText(_translate("Form", "亲和能："))
        self.Eg.setText(_translate("Form", "1.12"))
        self.Eg.setPlaceholderText(_translate("Form", "  禁带宽度"))
        self.Qm.setText(_translate("Form", "4.26"))
        self.Qm.setPlaceholderText(_translate("Form", "  禁带宽度"))
        self.label_24.setText(_translate("Form", "功函数："))
        self.es.setText(_translate("Form", "11.7 * 8.85 * 10 ** (-14)"))
        self.es.setPlaceholderText(_translate("Form", "  介电常数"))
        self.label_23.setText(_translate("Form", " F/CM"))
        self.label_20.setText(_translate("Form", " Eg： "))
        self.label_19.setText(_translate("Form", "介电常数： "))
        self.label_17.setText(_translate("Form", "  /cm^-3 "))
        self.label_9.setText(_translate("Form", " ni： "))
        self.XX.setText(_translate("Form", "4.01"))
        self.XX.setPlaceholderText(_translate("Form", "  禁带宽度"))
        self.ni.setText(_translate("Form", "1.5 * (10 ** 10)"))
        self.ni.setPlaceholderText(_translate("Form", "  本征载流子浓度"))
        self.groupBox_7.setTitle(_translate("Form", "衬底"))
        self.Si.setText(_translate("Form", "硅（Si）"))
        self.Ge.setText(_translate("Form", "锗（Ge）"))
        self.GaAs.setText(_translate("Form", "砷化镓（GaAs）"))
        self.groupBox_8.setTitle(_translate("Form", "金属"))
        self.Al.setText(_translate("Form", "Al"))
        self.Ag.setText(_translate("Form", "Ag"))
        self.An.setText(_translate("Form", "An"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "materials"))
        self.groupBox_9.setTitle(_translate("Form", "衬底类型"))
        self.label_39.setText(_translate("Form", " /cm^-3"))
        self.P.setText(_translate("Form", "    P型"))
        self.N.setText(_translate("Form", "N型"))
        self.NN.setText(_translate("Form", "2 * ( 10 ** 16)"))
        self.label_38.setText(_translate("Form", "掺杂浓度：  "))
        self.Qss.setText(_translate("Form", "5 * ( 10 ** 11)"))
        self.label_47.setText(_translate("Form", "  V"))
        self.label_45.setText(_translate("Form", " CM"))
        self.L.setText(_translate("Form", "1.25 * 10 ** (-4)"))
        self.label_46.setText(_translate("Form", " /cm^-2"))
        self.dffeedf.setText(_translate("Form", "VGS：  "))
        self.rhgdg.setText(_translate("Form", "Qss：  "))
        self.W.setText(_translate("Form", "11.8 * 10 ** (-4)"))
        self.label_40.setText(_translate("Form", "L：  "))
        self.label_44.setText(_translate("Form", " CM"))
        self.wewwrfqwf.setText(_translate("Form", "W："))
        self.dffeedf_2.setText(_translate("Form", "tox：  "))
        self.tox.setText(_translate("Form", "12 * 10 ** (-7)"))
        self.label_48.setText(_translate("Form", " CM"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "structure"))
        self.groupBox_6.setTitle(_translate("Form", "仿真项目"))
        self.Ge_2.setText(_translate("Form", "n沟道MOSFET阈值电压与掺杂浓度的关系"))
        self.Ge_3.setText(_translate("Form", "p沟道MOSFET阈值电压与掺杂浓度的关系"))
        self.Ge_4.setText(_translate("Form", "最大空间电荷区宽度与掺杂浓度的关系"))
        self.Ge_5.setText(_translate("Form", "电子反型电荷密度与表面电势的关系"))
        self.Ge_8.setText(_translate("Form", "电子反型电荷密度与表面电势（对数坐标）"))
        self.Ge_6.setText(_translate("Form", "n沟道耗尽型MOSFET的I-V特性曲线簇"))
        self.Ge_7.setText(_translate("Form", "n沟道耗尽型MOSFET的转移特性曲线"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "Item_simulation"))
        self.pushButton_2.setText(_translate("Form", "快速运算"))
        self.groupBox.setTitle(_translate("Form", "输出结果"))
        self.klnddvko.setText(_translate("Form", " Qfn:"))
        self.Qfn.setPlaceholderText(_translate("Form", "  EFi与EF之间的势垒高度"))
        self.label_10.setText(_translate("Form", "   V"))
        self.skjdhfbvk.setText(_translate("Form", " Xdt: "))
        self.Xdt.setPlaceholderText(_translate("Form", "  最大空间电荷宽度"))
        self.label_11.setText(_translate("Form", "  CM"))
        self.Emax1.setText(_translate("Form", "Qsdmax:"))
        self.Qsdmax.setPlaceholderText(_translate("Form", "  耗尽层电荷密度最大值"))
        self.label_12.setText(_translate("Form", "  C/CM^2"))
        self.label_7.setText(_translate("Form", " Qms :"))
        self.Qms.setPlaceholderText(_translate("Form", "  金属—半导体功函数差"))
        self.label_13.setText(_translate("Form", "   V"))
        self.label_6.setText(_translate("Form", " VTP:"))
        self.VTP.setPlaceholderText(_translate("Form", "  P沟道阈值电压"))
        self.label_14.setText(_translate("Form", "   V"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.NCD), _translate("Form", "N衬底"))
        self.klnddvko_2.setText(_translate("Form", " Qfp:"))
        self.Qfn_2.setPlaceholderText(_translate("Form", "  EFi与EF之间的势垒高度"))
        self.label_28.setText(_translate("Form", "   V"))
        self.skjdhfbvk_2.setText(_translate("Form", " Xdt: "))
        self.Xdt_2.setPlaceholderText(_translate("Form", "  最大空间电荷宽度"))
        self.label_18.setText(_translate("Form", "  CM"))
        self.Emax1_2.setText(_translate("Form", "Qsdmax:"))
        self.Qsdmax_2.setPlaceholderText(_translate("Form", "  耗尽层电荷密度最大值"))
        self.label_15.setText(_translate("Form", "  C/CM^2"))
        self.label_8.setText(_translate("Form", " Qms :"))
        self.Qms_2.setPlaceholderText(_translate("Form", "  金属—半导体功函数差"))
        self.label_27.setText(_translate("Form", "   V"))
        self.label_29.setText(_translate("Form", " VTN:"))
        self.VTP_2.setPlaceholderText(_translate("Form", "  P沟道阈值电压"))
        self.label_26.setText(_translate("Form", "   V"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.PCD), _translate("Form", "P衬底"))
        self.groupBox_3.setTitle(_translate("Form", "主程序"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "仿真结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "器件文档"))
        self.groupBox_4.setTitle(_translate("Form", "功能按钮"))
        self.pushButton.setText(_translate("Form", "清空画布"))
        self.pushButton_1.setText(_translate("Form", "保存图像"))
        self.radioButton.setText(_translate("Form", "100dpi"))
        self.radioButton_1.setText(_translate("Form", "300dpi"))
        self.runButton.setText(_translate("Form", "开始仿真"))
        self.exit.setText(_translate("Form", "退出系统"))

